wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.30
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      4: 3.8.5
      5: 0.10.30
      8:
      - 5
backend:
  desc: null
  value: MPI
batch_size:
  desc: null
  value: 256
ci:
  desc: null
  value: 0
client_num_in_total:
  desc: null
  value: 2
client_num_per_round:
  desc: null
  value: 2
client_optimizer:
  desc: null
  value: sgd
comm_round:
  desc: null
  value: 400
data_dir:
  desc: null
  value: ./../../../data/mnist
dataset:
  desc: null
  value: mnist
epochs:
  desc: null
  value: 1
frequency_of_the_test:
  desc: null
  value: 1
gpu_mapping_file:
  desc: null
  value: null
gpu_mapping_key:
  desc: null
  value: null
gpu_num_per_server:
  desc: null
  value: 4
gpu_server_num:
  desc: null
  value: 1
grpc_ipconfig_path:
  desc: null
  value: grpc_ipconfig.csv
is_mobile:
  desc: null
  value: 1
lr:
  desc: null
  value: 0.1
model:
  desc: null
  value: cnn
partition_alpha:
  desc: null
  value: 0.5
partition_method:
  desc: null
  value: hetero
wd:
  desc: null
  value: 0.0001
